language: php

php:
  - 5.4
  - 5.3
  - 5.5

install:
  - composer install
  - pip install coveralls

script:
    - nosetests --with-coverage --cover-package=asimpleforum
after_success:
    - coveralls
